### ISSUE TITLE
Clarify that this is not official distribution

### ISSUE THREAD

**Issue by jeffmcneill** [Autossh/autossh#7]
This is copy and paste from https://www.harding.motd.ca/autossh/ without any notification as such. In other words this repository is deceptive, and also has no real reason for existing.

**Comment by hanrea** [comment]
This exists for the convenience of pulling code, and some countries cannot access the source website. @jeffmcneill  Are you the developer of Autossh? I will transfer ownership to you?

**Comment by jeffmcneill** [comment]
So, why don't you write at at the top of the READ ME page? And for goodness sake update to the latest release, as per the very first issue on this repository! https://github.com/Autossh/autossh/issues/1

**Comment by hanrea** [comment]
@jeffmcneill All the files are original, and I haven't used them for the past two years, so can you take over it? I have already sent you an invitation

**Comment by jeffmcneill** [comment]
Not interested, thank you. I think this repository should just go away. After all `autossh` is in the repository of all major distributions, in any case.

**Comment by hanrea** [comment]
updated ! @jeffmcneill   I don't use Autossh for profit, creating this branch is just for convenience. The organization is open and anyone can apply to join for update !
